# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Innes' Blog Site
email: 
description: > # this means to ignore newlines until "baseurl:"
  IT Pro blog site, content generally about PowerShell.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexinnes.github.io" # the base hostname & protocol for your site
twitter_username: alexinnes
github_username:  alexinnes
cover_image: "/ps.png"
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
excerpt_separator: <!--more-->


kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-menus
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-menus
